modLoader="javafml"
loaderVersion="[1,)"
license="MPL-2.0"

[[mods]]
modId="hqspeaker"
version="${file.jarVersion}"
displayName="CC:HQ Speakers"
authors="tom"
description='''
High-quality upgrade layer for CC:Tweaked speaker blocks.
Uses the normal computercraft:speaker block, adding modern MP3/WAV playback, multispeaker control, RAW PCM, and optional stream/ICY helpers.
'''

[[mixins]]
config="hqspeaker.mixins.json"

[[dependencies.hqspeaker]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.hqspeaker]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.hqspeaker]]
modId="computercraft"
type="required"
versionRange="[1.120.0,1.121)"
ordering="AFTER"
side="BOTH"
